<a href="https://colab.research.google.com/github/nvr98/Demo2/blob/master/Logistic_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [4]:
dataset = pd.DataFrame(pd.read_csv('Social_Network_Ads.csv'))

x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

len(x), len(y)

(400, 400)

In [11]:
#Training and test data

X_train , X_test ,Y_train , Y_test  = train_test_split(x,y , test_size=0.2 , random_state=42)

len(X_train) , len(X_test),len(Y_train),len(Y_test)
X_train

array([[    27,  57000],
       [    46,  28000],
       [    39, 134000],
       [    44,  39000],
       [    57,  26000],
       [    32, 120000],
       [    41,  52000],
       [    48,  74000],
       [    26,  86000],
       [    22,  81000],
       [    49,  86000],
       [    36,  54000],
       [    40,  59000],
       [    41,  80000],
       [    26,  16000],
       [    39,  79000],
       [    59, 130000],
       [    42,  64000],
       [    53, 143000],
       [    34, 112000],
       [    57, 122000],
       [    39,  71000],
       [    47,  25000],
       [    24,  19000],
       [    36,  50000],
       [    32, 150000],
       [    48,  29000],
       [    30, 107000],
       [    60,  34000],
       [    38,  61000],
       [    33,  31000],
       [    39,  71000],
       [    55,  39000],
       [    49,  39000],
       [    43, 112000],
       [    27,  20000],
       [    26,  17000],
       [    37,  93000],
       [    42,  54000],
       [    35,  61000],


In [13]:
#Since it is a classification problem the feature needs to be scaled to a uniform range of value

from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [20]:
# Creating the logistic regression model

from sklearn.linear_model import LogisticRegression

classifier = LogisticRegression(random_state = 45)

classifier.fit(X_train,Y_train)

LogisticRegression(random_state=45)

In [23]:
Y_pred = classifier.predict(X_test)


In [22]:
Y_test

array([0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1])

In [25]:
#Compairing the results of Classifier and origingal dataset 
np.concatenate([Y_pred.reshape(len(Y_pred),1),Y_test.reshape(len(Y_test),1)],1)

array([[0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 0],
       [1, 1],
       [1, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [0, 1],
       [1, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 1],
       [0, 0],
       [0, 0],
       [0, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 1],
       [1,

In [33]:
classifier.predict(sc.transform([[30,100000]]))

array([0])

In [39]:
#Confusion matrix

from sklearn.metrics import confusion_matrix , accuracy_score

cm = confusion_matrix

print(cm(Y_test , Y_pred))

accuracy_score(Y_test , Y_pred)

[[49  3]
 [ 8 20]]


0.8625